# Generated by Django 5.2.7 on 2025-10-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plastic_images/')),
                ('identified_plastic', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField()),
                ('pressure_psi', models.FloatField()),
                ('speed_rpm', models.FloatField()),
                ('viscosity_pas', models.FloatField()),
                ('hours_since_maintenance', models.FloatField()),
                ('cycle_time_s', models.FloatField()),
                ('predicted_quality', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
